<a href="https://colab.research.google.com/github/SaiRishi2003/Covid_19/blob/main/notebook6e3d5ceade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/latese-dt-31082021/Latest Covid-19 India Status.csv

In [ ]:
#importing the necessary libraries

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import warnings
warnings.simplefilter('ignore')

In [ ]:
df = pd.read_csv('../input/latese-dt-31082021/Latest Covid-19 India Status.csv')
df

,State/UTs,Total Cases,Active,Discharged,Deaths,Active Ratio (%),Discharge Ratio (%),Death Ratio (%)
0,Andaman and Nicobar,7560,10,7421,129,0.13,98.16,1.71
1,Andhra Pradesh,2004590,13677,1977163,13750,0.68,98.63,0.69
2,Arunachal Pradesh,52409,1127,51023,259,2.15,97.36,0.49
3,Assam,585689,8005,572084,5600,1.37,97.68,0.96
4,Bihar,725605,102,715853,9650,0.01,98.66,1.33
5,Chandigarh,65069,35,64222,812,0.05,98.70,1.25
6,Chhattisgarh,1004230,653,990022,13555,0.07,98.59,1.35
7,Dadra and Nagar Haveli and Daman and Diu,10659,4,10651,4,0.04,99.92,0.04
8,Delhi,1437485,411,1411995,25079,0.03,98.23,1.74
9,Goa,173357,932,169239,3186,0.54,97.62,1.84
10,Gujarat,825330,160,815091,10079,0.02,98.76,1.22
11,Haryana,770380,664,760047,9669,0.09,98.66,1.26
12,Himachal Pradesh,212260,2054,206628,3578,0.97,97.35,1.69
13,Jammu and Kashmir,324420,1055,318961,4404,0.33,98.32,1.36
14,Jharkhand,347755,153,342470,5132,0.04,98.48,1.48
15,Karnataka,2941026,19810,2884032,37184,0.67,98.06,1.26
16,Kerala,3851984,159870,3672357,19757,4.15,95.34,0.51
17,Ladakh,20500,55,20238,207,0.27,98.72,1.01
18,Lakshadweep,10318,28,10239,51,0.27,99.23,0.49
19,Madhya Pradesh,792109,84,781509,10516,0.01,98.66,1.33
20,Maharashtra,6432649,53260,6243034,136355,0.83,97.05,2.12
21,Manipur,111598,3610,106229,1759,3.23,95.19,1.58
22,Meghalaya,74232,2820,70127,1285,3.80,94.47,1.73
23,Mizoram,54057,6664,47192,201,12.33,87.30,0.37
24,Nagaland,29669,888,28170,611,2.99,94.95,2.06
25,Odisha,1002323,7461,987369,7493,0.74,98.51,0.75
26,Puducherry,123007,765,120433,1809,0.62,97.91,1.47
27,Punjab,600342,423,583564,16355,0.07,97.21,2.72
28,Rajasthan,954040,128,944958,8954,0.01,99.05,0.94
29,Sikkim,29477,1548,27562,367,5.25,93.50,1.25
30,Tamil Nadu,2604074,18603,2550710,34761,0.71,97.95,1.33
31,Telengana,655732,6276,645594,3862,0.96,98.45,0.59
32,Tripura,82384,1113,80480,791,1.35,97.69,0.96
33,Uttar Pradesh,1709152,352,1686006,22794,0.02,98.65,1.33
34,Uttarakhand,342786,310,335099,7377,0.09,97.76,2.15
35,West Bengal,1544109,9217,1516509,18383,0.60,98.21,1.19